trigger:
  batch: true

variables:
  # Change the following along with adding new TEST_START_INDEX.
  TEST_COUNT: 15

jobs:
- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: Linux
    vmImage: ubuntu-20.04
    matrix:
      py311_np200_0:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 0
      py311_np200_1:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 1
      py311_np200_2:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 2
      py311_np200_3:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 3
      py311_np200_4:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 4
      py311_np200_5:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 5
      py311_np200_6:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 6
      py311_np200_7:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 7
      py311_np200_8:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 8
      py311_np200_9:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 9
      py311_np200_10:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 10
      py311_np200_11:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 11
      py311_np200_12:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 12
      py311_np200_13:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 13
      py311_np200_14:
        PYTHON: '3.11'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 14
